### ISSUE TITLE
Error on Contao 3.5

### ISSUE THREAD

**Issue by Metis77** [psi-4ward/Lightbox4ward#22]
love you plugin.
Can you update it for Contao 3.5?
I just downloaded the "master"

I get this error:
failed to open stream: No such file or directory in system/modules/core/library/Contao/ClassLoader.php on line 148

Of course I offer my monetary support.

**Comment by psi-4ward** [comment]
Tested on Contao 3.5.15, installed using Composer.
Works pretty good for me
