### ISSUE TITLE
Fataler Fehler wenn Bilddatei zu Bildlink fehlt

### ISSUE THREAD

**Issue by ThomasWeiser** [psi-4ward/Lightbox4ward#23]
Ich verwende lightbox4ward (3.0.1) und benutze Bildlinks in den lightbox4ward-Elementen.

Wenn mein Kunde in der Dateiverwaltung (warum auch immer) die zugehörige Bilddatei löscht, bricht die Seite mit dieser Fehlermeldung ab:

```
[30-Oct-2016 18:27:13 GMT] PHP Fatal error: Uncaught exception 'TypeError' with message 'Argument 1 passed to Contao\Image::__construct() must be an instance of Contao\File, null given, called in [...]/system/modules/core/library/Contao/Image.php on line 898' thrown in [...]/system/modules/core/library/Contao/Image.php on line 107
#0 [...]/system/modules/core/library/Contao/Image.php(898): Contao\Image->__construct(NULL)
#1 [...]/system/modules/core/library/Contao/Controller.php(1534): Contao\Image::create(NULL, Array)
#2 [...]/system/modules/lightbox4ward/ContentLightbox4ward.php(42): Contao\Controller::addImageToTemplate(Object(Contao\FrontendTemplate), Array)
#3 [...]/system/modules/core/elements/ContentElement.php(265): ContentLightbox4ward->compile()
#4 [...]/system/modules/core/library/Contao/Controller.php(484): Contao\ContentElement->generate()
#5 [...]/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#6 [...]/system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#7 [...]/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#8 [...]/system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#9 [...]/system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#10 [...]/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#11 [...]/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#12 [...]/index.php(20): Contao\FrontendIndex->run()
#13 {main}
```

Unangenehm ist, dass auch im Backend der beinhaltende Artikel nicht mehr bearbeitet werden kann.

Mein bisheriger Workaround: Korrigiere in der Datenbank im entsprechenden `tl_content`-Eintrag den Wert von `singleSRC`, so dass dort wieder die `uuid` eines vorhandenen Bildes steht.

Ist das ein bekanntes Problem? Kann ich es irgendwie vermeiden? Mache ich was falsch?

**Comment by psi-4ward** [comment]
Hmm ja diesen case könnte Lightbox4ward abfangen aber was wäre denn das erwartet Verhalten?
Das Bild fehlt bzw der Bildlink wird nicht dargestellt. Der Fehler würde dann geschluckt werden.

**Comment by ThomasWeiser** [comment]
Danke für die schnelle Antwort!

Das Standardverhalten von Contao bei fehlenden Bildern ist, nichts zu rendern, was vermutlich das sinnvollste ist.

Am wichtigsten wäre jedoch, dass der Artikel im Backend weiterhin editierbar ist. Das ist zu Zeit nicht der Fall.

**Comment by psi-4ward** [comment]
Bitte testen!

**Comment by ThomasWeiser** [comment]
Getestet: Funktioniert wie erwartet.

(Man könnte sich von Contao allgemein noch wünschen, dass fehlende Dateien im `error.log` vermerkt werden. Dies ist aber anscheinend etwa bei `ce_image` auch nicht der Fall.)

Vielen Danke für den schellen Fix und generell für die feine Erweiterung!

**Comment by psi-4ward** [comment]
Da müsste man zumindest nen debounce einbauen da sonst das Log extrem schnell extrem groß werden könnte.

**Comment by ThomasWeiser** [comment]
Ok, stimmt. Gibt es ev. eine Möglichkeit / eine Erweiterung, ungültige Referenzen (`singleSRC` nicht in der Dateiverwaltung) zu suchen und anzuzeigen?

**Comment by psi-4ward** [comment]
Mir ist nichts bekannt.

**Comment by ThomasWeiser** [comment]
Danke
